import { useState } from 'react'
import { ArrowRight, BookOpen, CalendarDays, Camera, CheckCircle2, Clock3, Globe, Headphones, Heart, Mail, MapPin, Menu, MessageCircle, Phone, Plane, PlayCircle, ShieldCheck, Star, UserRound, Users, X } from 'lucide-react'

const tours = [
  { tag:'Thiên nhiên', title:'Thành Đô – Cửu Trại Câu – Tứ Cô Nương', info:'6N5Đ • Thiên nhiên', image:'/assets/tour-jiuzhaigou.jpg' },
  { tag:'Di sản', title:'Bắc Kinh – Thượng Hải', info:'6N5Đ • Di sản – Thành phố', image:'/assets/tour-beijing.jpg' },
  { tag:'Cung đường đẹp', title:'Đại Lý – Lệ Giang – Shangrila', info:'6N5Đ • Cung đường đẹp', image:'/assets/tour-lijiang.jpg' },
  { tag:'Di sản – Văn hóa', title:'Thanh Hải – Cam Túc / Tây An – Lạc Dương', info:'7N6Đ • Di sản – Văn hóa', image:'/assets/tour-qinghai.jpg' },
  { tag:'Thiên nhiên – Văn hóa', title:'Quế Lâm – Dương Sóc / Tour đường bộ', info:'6N5Đ • Thiên nhiên – Văn hóa', image:'/assets/tour-guilin.jpg' },
]

function LeadFields(){return <div className="lead-fields">
  <label><span><MapPin/> Tuyến tour</span><select defaultValue="cd"><option value="cd">Thành Đô – Cửu Trại Câu</option><option value="bk">Bắc Kinh – Thượng Hải</option><option value="dl">Đại Lý – Lệ Giang – Shangrila</option><option value="ta">Tây An – Lạc Dương</option><option value="ql">Quế Lâm – Dương Sóc</option></select></label>
  <label><span><Users/> Số khách</span><select defaultValue="2"><option value="1">1 người</option><option value="2">2 người</option><option value="4">3–4 người</option><option value="5">Trên 5 người</option></select></label>
  <label><span><CalendarDays/> Thời gian dự kiến</span><select defaultValue="10"><option value="9">Tháng 09/2026</option><option value="10">Tháng 10/2026</option><option value="11">Tháng 11/2026</option><option value="12">Tháng 12/2026</option></select></label>
</div>}

function Modal({tour,onClose}){const [sent,setSent]=useState(false);return <div className="modal-overlay" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modal-close" aria-label="Đóng" onClick={onClose}><X/></button><h2 id="modal-title">{sent?'Đã nhận yêu cầu của bạn':'Nhận tư vấn nhanh'}</h2><p>{sent?'Seven Travel sẽ liên hệ tư vấn trong vòng 15 phút.':'Để lại thông tin, chuyên viên Seven Travel sẽ gửi lịch trình và báo giá phù hợp.'}</p>{sent?<div className="success"><CheckCircle2/><p>Cảm ơn bạn đã quan tâm đến hành trình<br/><strong>{tour}</strong>.</p><button onClick={onClose}>Hoàn tất</button></div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>Họ và tên<input required placeholder="Nguyễn Minh Anh"/></label><label>Số điện thoại<input required type="tel" placeholder="09xx xxx xxx"/></label><label>Tour quan tâm<input readOnly value={tour}/></label><button type="submit">Gửi yêu cầu tư vấn</button><small><ShieldCheck/> Thông tin của bạn được bảo mật tuyệt đối</small></form>}</section></div>}

export default function App(){
 const [selectedTour,setSelectedTour]=useState(''); const [emailSent,setEmailSent]=useState(false); const [mobileMenu,setMobileMenu]=useState(false)
 const openLead=(tour='Thành Đô – Cửu Trại Câu')=>setSelectedTour(tour)
 return <main>
  <header className="site-header"><a className="brand" href="#"><img src="/assets/seven-travel-logo.png" alt="SevenTravel"/></a><nav className={mobileMenu?'open':''}><a className="active" href="#">Trang chủ</a><a href="#tours">Tour Trung Quốc</a><a href="#tours">Điểm đến</a><a href="#tours">Lịch khởi hành</a><a href="#stories">Cẩm nang</a><a href="#trust">Về chúng tôi</a></nav><div className="header-actions"><button className="language-switch" aria-label="Chuyển đổi ngôn ngữ"><Globe/><strong>VIE</strong><i>/</i><span>ENG</span></button><button className="icon-button" aria-label="Danh sách yêu thích"><Heart/></button><button className="login-button">Đăng nhập</button></div><button className="menu" aria-label="Mở menu" onClick={()=>setMobileMenu(!mobileMenu)}><Menu/></button></header>
  <section className="hero"><div className="hero-shade"/><div className="hero-content"><div className="hero-copy visual-hero"><h1><span>CHẠM VÀO</span><span>KỲ QUAN TRUNG HOA</span></h1><p className="hero-destinations">Bắc Kinh <i>•</i> Thượng Hải <i>•</i> Trương Gia Giới <i>•</i> Phượng Hoàng Cổ Trấn <i>•</i> Lệ Giang</p><p className="hero-selling">Tour bay thẳng <i>•</i> Visa nhanh chóng <i>•</i> Khách sạn 4-5 sao</p><a className="hero-hotline" href="tel:0899525777"><Phone/> Hotline: 0899 525 777</a></div><div className="lead-card"><h2>Bạn muốn khám phá tuyến nào?</h2><LeadFields/><button className="lead-cta" onClick={()=>openLead()}>Nhận lịch trình &amp; Báo giá <Plane/></button><div className="micro"><span><Phone/> Miễn phí tư vấn</span><i>•</i><span><Clock3/> Phản hồi trong 15 phút</span></div></div></div></section>
  <section id="tours" className="tours-section"><div className="section-head"><div><span className="section-kicker">HÀNH TRÌNH ĐƯỢC YÊU THÍCH</span><h2>Chùm tour Trung Quốc nổi bật</h2></div><p>Những cung đường đặc sắc nhất, được đội ngũ Seven Travel chọn lọc kỹ lưỡng.</p></div><div className="tour-grid">{tours.map(t=><article className="tour-card" key={t.title}><div className="tour-image"><img src={t.image} alt={t.title}/><span>{t.tag}</span></div><div className="tour-body"><h3>{t.title}</h3><p><Clock3/> {t.info}</p><button onClick={()=>openLead(t.title)}>Nhận tư vấn</button></div></article>)}</div></section>
  <section id="trust" className="trust"><h2><Plane/> Khởi hành linh hoạt <span>–</span> Lịch trình chọn lọc <span>–</span> Hỗ trợ visa tận tâm</h2><div className="trust-grid"><article><BookOpen/><div><h3>Hỗ trợ visa</h3><p>Tư vấn và hướng dẫn thủ tục đầy đủ</p></div></article><article><UserRound/><div><h3>Hướng dẫn viên chuyên tuyến</h3><p>Am hiểu điểm đến, tận tâm đồng hành</p></div></article><article><Headphones/><div><h3>Hỗ trợ 24/7</h3><p>Đội ngũ tư vấn luôn sẵn sàng hỗ trợ bạn</p></div></article><article><div className="stars"><Star/><Star/><Star/><Star/><Star/></div><div><h3>4.9/5 từ khách hàng</h3><p>Đánh giá cao về chất lượng dịch vụ và trải nghiệm</p></div></article></div></section>
  <section className="offer-block"><div className="offer-photo"/><div className="offer-copy"><span>ƯU ĐÃI HÀNH TRÌNH ĐẦU TIÊN</span><h2>Hành trình của bạn,<br/>theo cách bạn muốn</h2><p>Đăng ký ngay để nhận <strong>ưu đãi 10%</strong> cho tour đầu tiên!</p>{emailSent?<div className="offer-success"><CheckCircle2/> Cảm ơn bạn! Ưu đãi sẽ được gửi qua email.</div>:<form onSubmit={e=>{e.preventDefault();setEmailSent(true)}}><label><Mail/><input required type="email" aria-label="Email nhận ưu đãi" placeholder="Nhập email của bạn"/></label><button>Nhận ưu đãi ngay <ArrowRight/></button></form>}</div></section>
  <section className="stories" id="stories"><div className="stories-heading"><div><span>CÂU CHUYỆN &amp; KINH NGHIỆM</span><h2>Cảm hứng du lịch Trung Quốc</h2></div><a href="#stories">Xem tất cả bài viết <ArrowRight/></a></div><div className="story-grid"><article><img src="/assets/story-old-town.jpg" alt="Phố cổ Trung Quốc về đêm"/><div><span>CẨM NANG DU LỊCH</span><h3>10 trải nghiệm nhất định phải thử khi đến Trung Quốc</h3><p>20/08/2026 · 5 phút đọc</p><a href="#stories">Đọc bài viết <ArrowRight/></a></div></article><article><img src="/assets/story-great-wall.jpg" alt="Vạn Lý Trường Thành trên núi"/><div><span>MẸO DU LỊCH</span><h3>Du lịch Trung Quốc – Thời điểm nào đẹp nhất?</h3><p>16/08/2026 · 5 phút đọc</p><a href="#stories">Đọc bài viết <ArrowRight/></a></div></article><article><img src="/assets/story-forbidden-city.webp" alt="Kiến trúc Tử Cấm Thành Trung Quốc"/><div><span>TRẢI NGHIỆM VĂN HÓA</span><h3>Văn hóa Trung Quốc: Phong tục, ứng xử và điều cần biết</h3><p>12/08/2026 · 5 phút đọc</p><a href="#stories">Đọc bài viết <ArrowRight/></a></div></article></div></section>
  <footer className="site-footer"><div className="footer-grid"><div className="footer-brand"><div className="footer-logo"><img src="/assets/seven-travel-logo.png" alt="SevenTravel"/></div><p>SevenTravel đồng hành cùng bạn khám phá những hành trình Trung Quốc chọn lọc và tạo nên những kỷ niệm đáng nhớ suốt đời.</p><div className="footer-social"><a href="#" aria-label="Facebook"><Globe/></a><a href="#" aria-label="Instagram"><Camera/></a><a href="#" aria-label="YouTube"><PlayCircle/></a></div></div><div><h3>Khám phá</h3><a href="#tours">Tour Trung Quốc</a><a href="#tours">Điểm đến</a><a href="#stories">Cẩm nang du lịch</a><a href="#trust">Trải nghiệm</a><a href="#">Liên hệ</a></div><div><h3>Hỗ trợ</h3><a href="#">Câu hỏi thường gặp</a><a href="#">Chính sách đặt tour</a><a href="#">Điều khoản sử dụng</a><a href="#">Chính sách bảo mật</a><a href="#">Hỗ trợ 24/7</a></div><div><h3>Điểm đến phổ biến</h3><a href="#">Cửu Trại Câu</a><a href="#">Bắc Kinh</a><a href="#">Lệ Giang</a><a href="#">Shangrila</a><a href="#">Quế Lâm</a></div><div className="footer-news"><h3>Nhận ưu đãi</h3><p>Đăng ký để nhận ưu đãi độc quyền và cảm hứng du lịch mỗi tuần.</p><form onSubmit={e=>e.preventDefault()}><input type="email" aria-label="Email nhận bản tin" placeholder="Nhập email của bạn"/><button aria-label="Đăng ký"><ArrowRight/></button></form></div></div><div className="footer-bottom"><span>© 2026 SevenTravel. Bảo lưu mọi quyền.</span><div><b>VISA</b><b>Mastercard</b><b>MoMo</b><b>ZaloPay</b></div></div></footer>
  <aside className="floating-social" aria-label="Liên hệ nhanh"><a className="whatsapp" href="https://wa.me/" target="_blank" rel="noreferrer" aria-label="Liên hệ WhatsApp"><MessageCircle/></a><a className="messenger" href="https://m.me/" target="_blank" rel="noreferrer" aria-label="Liên hệ Facebook Messenger"><img src="/assets/messenger.png" alt="Messenger" style={{ width: '56px', height: '56px', objectFit: 'contain' }} /></a><a className="zalo" href="https://zalo.me/0899525777/" target="_blank" rel="noreferrer" aria-label="Liên hệ Zalo">Zalo</a></aside>
  <button className="mobile-lead" onClick={()=>openLead()}><Phone/> Nhận lịch trình &amp; Báo giá</button>{selectedTour&&<Modal tour={selectedTour} onClose={()=>setSelectedTour('')}/>} 
 </main>
}
